### ISSUE TITLE
Queue command broken in Music module.

### ISSUE THREAD

**Issue by xFuney** [xFuney/jolastu#4]
**Tested on**: iPod Discord Server

**Issue:** Queue command in the music module doesn't work.

**Any logs?:** Not as of yet, will obtain from host later.

**Comment by xFuney** [comment]
Log from host:
```js
(node:27195) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.fields[0].value: Must be 1024 or fewer in length.
    at RequestHandler.execute (/home/botuser/jolastu/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:27195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by xFuney** [comment]
Appears to be because we exceeded Discord's 1024 character limit on embed fields. I'll take a look at adding a cutoff to the queue later.

**Comment by xFuney** [comment]
Fixed in merged commit 49adad by bredo228. Issue will be closed but is subject to reopening if the issue is found again.
